### PR TITLE
Add directory tracking via OSC callback

### PR DESCRIPTION
**Pull request by akermu**
Solves #55

### CODE REVIEW

**Comment by jixiuf** [comment]
got this when I change my directory 
```
Process:               Emacs [51720]
Path:                  /usr/local/emacs/Emacs.app/Contents/MacOS/Emacs
Identifier:            org.gnu.Emacs
Version:               Version 27.0.50 (9.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Emacs [51720]
User ID:               501

Date/Time:             2019-08-03 19:53:37.309 +0800
OS Version:            Mac OS X 10.14.4 (18E226)
Report Version:        12
Anonymous UUID:        DE267489-0414-BCF9-56BE-1F1736BCE81A

Sleep/Wake UUID:       3002698D-B3E9-48AF-8350-B0A480C443E3

Time Awake Since Boot: 180000 seconds
Time Since Wake:       2300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
Emacs(51720,0x1022b75c0) malloc: *** error for object 0x7fe983d5ea60: pointer being freed was not allocated
 

```

**Comment by akermu** [comment]
@jixiuf Should be fixed now.

**Comment by jixiuf** [comment]
LGTM.
any plan to support tramp

**Comment by akermu** [comment]
Yes, I want to implement support tramp at least behind a feature flag. But I have to think about how to do it unobtrusively as I don't want to have tramp error buffers pop up all over the place, when changing a directory.

**Pull request merged**
