### PR TITLE
Adding documentation.

### PR DESCRIPTION
**Pull request by mbrumlow**
The other PR was merged just after the request for some documentation. This is me adding that documentation.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
Thanks, @mbrumlow. This is fantastic.

Can I ask you to expand a little bit on the docstring in the elisp function?
Maybe you can explain what the fake newlines are (ie, why they are there. You can maybe copy from the comments in the C code).

This is to make sure that users can find more documentation from within Emacs.

**Comment by Sbozzolo** [comment]
Thanks, @mbrumlow.

A few comments. There are some guidelines for writing docstrings: https://www.gnu.org/software/emacs/manual/html_node/elisp/Documentation-Tips.html

In this case, the first line should be shorter, descriptive and should be imperative. Arguments should appear in the docstring and should be capitalized. 

It is also helpful to crosslink different dosctrings. For instance, the docstring for `vterm--filter-buffer-substring` is not very informative. Linking it to `vterm--remove-fake-newlines` would give the reader a pointer.

Also, neither of the docstrings really explain what are these fake new lines. Where is that they are tagged? Why do we need them?

**Comment by Sbozzolo** [comment]
@mbrumlow, it would be great if you implemented what discussed in my previous message. 
Are you still interested in doing that?

Thanks

**Comment by mbrumlow** [comment]
Yes, I will be working on this -- work has been busy, once I get some free time back I will be sure to address this issue.

**Pull request closed without merging**
