### PR TITLE
Update vterm-use-vterm-prompt docstring

### PR DESCRIPTION
**Pull request by PuercoPop**
Spell out which prompt tracking strategy is used for each value

Thanks for libvterm!

### CODE REVIEW

**Comment by Sbozzolo** [comment]
Thanks for your contribution. A couple of things:
1. In Emacs lisp any symbol that is not `nil` has value true. Therefore, instead of saying "if t", it is better to say "if not nil" (as according to official guidelines)
2. After periods there should be two spaces, not one.
3. Typically, docstrings start with a short description, have an empty line, and additional information after that.

In the spirit of improving the docstring you touched, I think it would be better to add a more in-depth description of what is the "vterm prompt tracker", when it should be used, and when not. If you can update your PR with this, that would be great.

**Comment by PuercoPop** [comment]
> 1. In Emacs lisp any symbol that is not nil has value true. Therefore, instead of saying "if t", it is better to say "if not nil" (as according to official guidelines)

Done. However I'll note that other defcustom docstrings in this package use 'if set to t' phrasing.

> 2. After periods there should be two spaces, not one.

Done.

> 3. Typically, docstrings start with a short description, have an empty line, and additional information after that.
> 
> In the spirit of improving the docstring you touched, I think it would be better to add a more in-depth description of what is the "vterm prompt tracker", when it should be used, and when not. If

I agree with that, however I don't think I am able to do a proper description of the custom option given that I've just started using this package and I'm not too familiar with its features yet. For example it appears that if the shell-side configuration is missing, even if `vterm-use-vterm-prompt` is set to `t`, `term-prompt-regex` is used as a fallback strategy?

The problem I address with the current docstring is that it is answering a 'Do you want A or B?' question with 'yes or no'. Given that yes or no is not an intelligible answer, after reading the docstring, the user is left wondering what option maps to which value.

**Comment by Sbozzolo** [comment]
I am sorry for the extremely long response time. I update and expand the commentary and docstrings in #364

**Comment by PuercoPop** [comment]
> I am sorry for the extremely long response time.

No need to apologize for how you choose to spend your free time. Thanks for updating the docs :tada:. Closing this PR as it is subsumed by #364 !

**Pull request closed without merging**
