### PR TITLE
Remove special default font and just use the default

### PR DESCRIPTION
**Pull request by hexmode**
See #162 for rationale.

### CODE REVIEW

**Comment by hexmode** [comment]
Oh, and, if it matters, I have a copyright assignment on file with the FSF.

**Comment by Sbozzolo** [comment]
Dear @hexmode, thanks for your contribution.

Your commit essentially reverts back 38bbd46745917f5d9e4062b94b729d92382de9d7, which granted users the possibility of choosing a different font for vterm. I don't fully grasp what is the problem with that, so I'll let @jixiuf (author of 38bbd46745917f5d9e4062b94b729d92382de9d7) take care of this PR.

**Comment by hexmode** [comment]
@jixiuf, @Sbozzolo:  I would suggest that the method I've given in #162 is the "right" way to set a default font for a mode.  At least, it seems to work for most other things.

**Comment by jixiuf** [comment]
can you mention that in readme about set a different font in vterm

**Comment by hexmode** [comment]
@jixiuf does that look good?

**Comment by Sbozzolo** [comment]
Thank you, @hexmode.

**Pull request merged**
