### PR TITLE
upgrade libvterm

### LINKED ISSUE #389: compilation error on mac
I was getting compilation error when trying to compile libvterm on my machine:

macOS Catalina version 10.15.6
had installed cmake and libtool with brew before compilation

image

I don't know if there's a better way to solve this, but my workaround solution was to add 
`#define _POSIX_C_SOURCE 200809L`
on top of `vterm-ctrl.c` file
I got this solution from https://stackoverflow.com/questions/26284110/strdup-confused-about-warnings-implicit-declaration-makes-pointer-with

I was wondering if any other people had similar issues trying to compile on mac and if there was a better solution. Also, was wondering if the source code can be updated.

### PR DESCRIPTION
**Pull request by jixiuf**
#403 
should fix  #389 

Edit: should ready to be reviewed.

### CODE REVIEW

**Comment by cwhatley** [comment]
FYI, I tried this branch on emacs 27.1/mac catalina and haven't run into any issues.

**Comment by Sbozzolo** [comment]
Thank you very much! That's great. I'll have a look.

**Comment by Sbozzolo** [comment]
I haven't looked at this in depth yet, but I think we should finish #410 first. This new PR makes the build system more fragile, so it would be great to have some form of continuous integration to run some smoke tests.

**Comment by olreim** [comment]
Works great. No issues. Emacs 27.1 running Doom 2.0.9 on macOS Catalina 10.15.6.

**Comment by jsigman** [comment]
I can currently only get vterm to work with this branch, using a Mac OS with the latest software and updates. It also runs on both 27.1 and also on the native-comp branch

**Pull request merged**
