### PR TITLE
Improves performance when receiving large bursts of data.

### PR DESCRIPTION
**Pull request by jixiuf**

### CODE REVIEW

**Comment by jixiuf** [comment]
update

**Comment by deb0ch** [comment]
Why would anyone opt-in (or not opt-in) to this ?

**Comment by jixiuf** [comment]
big improvement after last force-pushed  
by setting    ` process-adaptive-read-buffering`
```
(setq process-adaptive-read-buffering  nil)
```

**Comment by akermu** [comment]
Thanks again!

**Pull request merged**
