### PR TITLE
Dirty hack for local directory track

### PR DESCRIPTION
**Pull request by condy0919**

### CODE REVIEW

**Comment by condy0919** [comment]
@Sbozzolo @jixiuf

**Comment by jixiuf** [comment]
Currently  `Directory tracking and Prompt tracking`  are using one  escaped sequences `51;A`
Maybe we can add another escaped sequences  in case someone only want to enable one of them.
we can change 
```
vterm_prompt_end() {
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)";
}
PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'

```
to 
```
vterm_prompt_end() {
    vterm_printf "51;A";
}
PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'
###############################
add-zsh-hook -Uz chpwd (){
            vterm_printf "51;B$(whoami)@$(hostname):$(pwd)"
}
```
@Sbozzolo What do you think.

**Comment by Sbozzolo** [comment]
> Currently `Directory tracking and Prompt tracking` are using one escaped sequences `51;A`
> Maybe we can add another escaped sequences in case someone only want to enable one of them.
> we can change
> 
> ```
> vterm_prompt_end() {
>     vterm_printf "51;A$(whoami)@$(hostname):$(pwd)";
> }
> PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'
> ```
> 
> to
> 
> ```
> vterm_prompt_end() {
>     vterm_printf "51;A";
> }
> PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'
> ###############################
> add-zsh-hook -Uz chpwd (){
>             vterm_printf "51;B$(whoami)@$(hostname):$(pwd)"
> }
> ```
> 
> @Sbozzolo What do you think.

Can you give me a use case? If one wants to have only the directory, they can already do it with the current infrastructure.

@condy0919, thanks for this contribution. Why/how do you use this? One problem I see is that the hack fail on remote machines, where I'd think it would be the most useful to have something that doesn't require the customization of the prompt.

**Comment by condy0919** [comment]
Yes, it works only on local machines. Document it in `README` to cheer up those who don't want to change the local shell configuration

**Comment by condy0919** [comment]
https://www.reddit.com/r/emacs/comments/gp7s4i/directory_tracking_in_ansiterm_with_without/

The reddit guy want local directory track without shell side configuration

**Comment by condy0919** [comment]
Close for #335

**Pull request closed without merging**
