### PR TITLE
Add remote directory tracking

### PR DESCRIPTION
**Pull request by akermu**
#55

### CODE REVIEW

**Comment by akermu** [comment]
Another solution would be to guess the user and domain from the terminal via a regexp. Then the user wouldn't have to modify their remote `.zshrc` or `.bashrc`.

**Comment by jixiuf** [comment]
> Another solution would be to guess the user and domain from the terminal via a regexp (probably via `tramp-shell-prompt-pattern`). Then the user wouldn't have to modify their remote `.zshrc` or `.bashrc`.

how ? I don't think we can  always guess the user,host and directory   ,different people may set different prompt .


and how about define some local variable like 
```
(defvar-local vterm-user "")
(defvar-local vterm-host "")
(defvar-local vterm-dir "")
```
and run a hook when directory changed.

**Comment by jixiuf** [comment]
Change my mind ,I approved it  ,let's keep it simple .

**Comment by jixiuf** [comment]
how about we change 
```
    print -Pn "\e]51;$(pwd)\e\\";
```
to 
```
    print -Pn "\e]51;A$(pwd)\e\\";
```
the difference is there is a `A` after `51;`
in case we add other osc_callback later
https://www.iterm2.com/documentation-escape-codes.html
like iterm use `^[]1337;` as the prefix of  non-standard escape codes

**Comment by akermu** [comment]
> how about we change
> 
> ```
>     print -Pn "\e]51;$(pwd)\e\\";
> ```
> 
> to
> 
> ```
>     print -Pn "\e]51;A$(pwd)\e\\";
> ```
> 
> the difference is there is a `A` after `51;`
> in case we add other osc_callback later
> https://www.iterm2.com/documentation-escape-codes.html
> like iterm use `^[]1337;` as the prefix of non-standard escape codes

This is a good idea, but `51` would be our `1337` or do I miss something?

**Comment by jixiuf** [comment]
yes ,51 would be our 1337

**Pull request merged**
